# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /export/home/kmjohnso/VIPR/RECON/unstable/mri-recon-code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /export/home/kmjohnso/VIPR/RECON/unstable/mri-recon-code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /export/home/kmjohnso/VIPR/RECON/unstable/mri-recon-code/CMakeFiles /export/home/kmjohnso/VIPR/RECON/unstable/mri-recon-code/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /export/home/kmjohnso/VIPR/RECON/unstable/mri-recon-code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named recon_binary

# Build rule for target.
recon_binary: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 recon_binary
.PHONY : recon_binary

# fast build rule for target.
recon_binary/fast:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/build
.PHONY : recon_binary/fast

ArrayTemplates.o: ArrayTemplates.cpp.o
.PHONY : ArrayTemplates.o

# target to build an object file
ArrayTemplates.cpp.o:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/ArrayTemplates.cpp.o
.PHONY : ArrayTemplates.cpp.o

ArrayTemplates.i: ArrayTemplates.cpp.i
.PHONY : ArrayTemplates.i

# target to preprocess a source file
ArrayTemplates.cpp.i:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/ArrayTemplates.cpp.i
.PHONY : ArrayTemplates.cpp.i

ArrayTemplates.s: ArrayTemplates.cpp.s
.PHONY : ArrayTemplates.s

# target to generate assembly for a file
ArrayTemplates.cpp.s:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/ArrayTemplates.cpp.s
.PHONY : ArrayTemplates.cpp.s

gridFFT.o: gridFFT.cpp.o
.PHONY : gridFFT.o

# target to build an object file
gridFFT.cpp.o:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/gridFFT.cpp.o
.PHONY : gridFFT.cpp.o

gridFFT.i: gridFFT.cpp.i
.PHONY : gridFFT.i

# target to preprocess a source file
gridFFT.cpp.i:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/gridFFT.cpp.i
.PHONY : gridFFT.cpp.i

gridFFT.s: gridFFT.cpp.s
.PHONY : gridFFT.s

# target to generate assembly for a file
gridFFT.cpp.s:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/gridFFT.cpp.s
.PHONY : gridFFT.cpp.s

mri_data.o: mri_data.cpp.o
.PHONY : mri_data.o

# target to build an object file
mri_data.cpp.o:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/mri_data.cpp.o
.PHONY : mri_data.cpp.o

mri_data.i: mri_data.cpp.i
.PHONY : mri_data.i

# target to preprocess a source file
mri_data.cpp.i:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/mri_data.cpp.i
.PHONY : mri_data.cpp.i

mri_data.s: mri_data.cpp.s
.PHONY : mri_data.s

# target to generate assembly for a file
mri_data.cpp.s:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/mri_data.cpp.s
.PHONY : mri_data.cpp.s

phantom.o: phantom.cpp.o
.PHONY : phantom.o

# target to build an object file
phantom.cpp.o:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/phantom.cpp.o
.PHONY : phantom.cpp.o

phantom.i: phantom.cpp.i
.PHONY : phantom.i

# target to preprocess a source file
phantom.cpp.i:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/phantom.cpp.i
.PHONY : phantom.cpp.i

phantom.s: phantom.cpp.s
.PHONY : phantom.s

# target to generate assembly for a file
phantom.cpp.s:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/phantom.cpp.s
.PHONY : phantom.cpp.s

recon.o: recon.cxx.o
.PHONY : recon.o

# target to build an object file
recon.cxx.o:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/recon.cxx.o
.PHONY : recon.cxx.o

recon.i: recon.cxx.i
.PHONY : recon.i

# target to preprocess a source file
recon.cxx.i:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/recon.cxx.i
.PHONY : recon.cxx.i

recon.s: recon.cxx.s
.PHONY : recon.s

# target to generate assembly for a file
recon.cxx.s:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/recon.cxx.s
.PHONY : recon.cxx.s

recon_lib.o: recon_lib.cpp.o
.PHONY : recon_lib.o

# target to build an object file
recon_lib.cpp.o:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/recon_lib.cpp.o
.PHONY : recon_lib.cpp.o

recon_lib.i: recon_lib.cpp.i
.PHONY : recon_lib.i

# target to preprocess a source file
recon_lib.cpp.i:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/recon_lib.cpp.i
.PHONY : recon_lib.cpp.i

recon_lib.s: recon_lib.cpp.s
.PHONY : recon_lib.s

# target to generate assembly for a file
recon_lib.cpp.s:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/recon_lib.cpp.s
.PHONY : recon_lib.cpp.s

softthreshold.o: softthreshold.cpp.o
.PHONY : softthreshold.o

# target to build an object file
softthreshold.cpp.o:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/softthreshold.cpp.o
.PHONY : softthreshold.cpp.o

softthreshold.i: softthreshold.cpp.i
.PHONY : softthreshold.i

# target to preprocess a source file
softthreshold.cpp.i:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/softthreshold.cpp.i
.PHONY : softthreshold.cpp.i

softthreshold.s: softthreshold.cpp.s
.PHONY : softthreshold.s

# target to generate assembly for a file
softthreshold.cpp.s:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/softthreshold.cpp.s
.PHONY : softthreshold.cpp.s

spirit.o: spirit.cpp.o
.PHONY : spirit.o

# target to build an object file
spirit.cpp.o:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/spirit.cpp.o
.PHONY : spirit.cpp.o

spirit.i: spirit.cpp.i
.PHONY : spirit.i

# target to preprocess a source file
spirit.cpp.i:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/spirit.cpp.i
.PHONY : spirit.cpp.i

spirit.s: spirit.cpp.s
.PHONY : spirit.s

# target to generate assembly for a file
spirit.cpp.s:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/spirit.cpp.s
.PHONY : spirit.cpp.s

temporal_diff.o: temporal_diff.cpp.o
.PHONY : temporal_diff.o

# target to build an object file
temporal_diff.cpp.o:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/temporal_diff.cpp.o
.PHONY : temporal_diff.cpp.o

temporal_diff.i: temporal_diff.cpp.i
.PHONY : temporal_diff.i

# target to preprocess a source file
temporal_diff.cpp.i:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/temporal_diff.cpp.i
.PHONY : temporal_diff.cpp.i

temporal_diff.s: temporal_diff.cpp.s
.PHONY : temporal_diff.s

# target to generate assembly for a file
temporal_diff.cpp.s:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/temporal_diff.cpp.s
.PHONY : temporal_diff.cpp.s

threshold.o: threshold.cpp.o
.PHONY : threshold.o

# target to build an object file
threshold.cpp.o:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/threshold.cpp.o
.PHONY : threshold.cpp.o

threshold.i: threshold.cpp.i
.PHONY : threshold.i

# target to preprocess a source file
threshold.cpp.i:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/threshold.cpp.i
.PHONY : threshold.cpp.i

threshold.s: threshold.cpp.s
.PHONY : threshold.s

# target to generate assembly for a file
threshold.cpp.s:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/threshold.cpp.s
.PHONY : threshold.cpp.s

wavelet3D.o: wavelet3D.cpp.o
.PHONY : wavelet3D.o

# target to build an object file
wavelet3D.cpp.o:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/wavelet3D.cpp.o
.PHONY : wavelet3D.cpp.o

wavelet3D.i: wavelet3D.cpp.i
.PHONY : wavelet3D.i

# target to preprocess a source file
wavelet3D.cpp.i:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/wavelet3D.cpp.i
.PHONY : wavelet3D.cpp.i

wavelet3D.s: wavelet3D.cpp.s
.PHONY : wavelet3D.s

# target to generate assembly for a file
wavelet3D.cpp.s:
	$(MAKE) -f CMakeFiles/recon_binary.dir/build.make CMakeFiles/recon_binary.dir/wavelet3D.cpp.s
.PHONY : wavelet3D.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... recon_binary"
	@echo "... ArrayTemplates.o"
	@echo "... ArrayTemplates.i"
	@echo "... ArrayTemplates.s"
	@echo "... gridFFT.o"
	@echo "... gridFFT.i"
	@echo "... gridFFT.s"
	@echo "... mri_data.o"
	@echo "... mri_data.i"
	@echo "... mri_data.s"
	@echo "... phantom.o"
	@echo "... phantom.i"
	@echo "... phantom.s"
	@echo "... recon.o"
	@echo "... recon.i"
	@echo "... recon.s"
	@echo "... recon_lib.o"
	@echo "... recon_lib.i"
	@echo "... recon_lib.s"
	@echo "... softthreshold.o"
	@echo "... softthreshold.i"
	@echo "... softthreshold.s"
	@echo "... spirit.o"
	@echo "... spirit.i"
	@echo "... spirit.s"
	@echo "... temporal_diff.o"
	@echo "... temporal_diff.i"
	@echo "... temporal_diff.s"
	@echo "... threshold.o"
	@echo "... threshold.i"
	@echo "... threshold.s"
	@echo "... wavelet3D.o"
	@echo "... wavelet3D.i"
	@echo "... wavelet3D.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

